### ISSUE TITLE
Document or mitigate undesired number formatting in `values.yaml`

### ISSUE THREAD

**Issue by 0x2b3bfa0** [iterative/helm-charts#603]
When e.g. `global.scmProviders.github.appId` is specified as a YAML number, rather than as a YAML string, it gets mangled by Helm and converted into scientific notation.

We should document this undesired behavior, or maybe even mitigate it for this specific field.

### Correct syntax

```yaml
global:
  scmProviders:
    github:
      appId "1200981"
```

### Upstream issue

* https://github.com/helm/helm/issues/1707
