### ISSUE TITLE
Add provision to inject additional environment variables to Studio

### ISSUE THREAD

**Issue by rishabhdas** [iterative/helm-charts#78]
Customer specific features are controlled through environment variables / flags. Need to extend Helm chart providing a way to inject customer specific environment variables through values.yaml / override file. 

For instance:

```yaml
extra_vars:
  - name: CUSTOMER_SPEC_VAR_1
     value: customer-variable-value-1
  - name: CUSTOMER_SPEC_VAR_2
     value: customer-variable-value-2
```

These can then be added to various studio components as needed.
