### ISSUE TITLE
Redis - support for non SSL protected environments

### ISSUE THREAD

**Issue by rishdasubs** [iterative/helm-charts#86]
Please provide a way to securely configure Redis connection using a secret and SSL. 

Use case is for using external Redis cache service instead of in-cluster. The service, by policy, has non-SSL port 6379 disabled. The service only accepts connections on port 6380 and is secured by a secret (access key / password).

**Comment by jesper7** [comment]
Hey Rishabh

I've checked, and it should already be supported in Studio. Can you please see if the following Helm values resolve the issue:

```yaml
global:
  celery:
    brokerUrl: rediss://<username>:<password>@<redis server>:<redis port>?ssl_cert_reqs=required
    resultBackend: rediss://<username>:<password>@<redis server>:<redis port>?ssl_cert_reqs=required
```

After you have included these in your existing values file, please redeploy the Helm chart.
